spring:
  profiles:
    active: dev
  application:
    name: passenger

  main:
    allow-circular-references: false

  mvc:
    problemdetails:
      enabled: true

  datasource:
    url: jdbc:postgresql://localhost:5433/passenger_write
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    entity-packages-to-scan: org.t13.app
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        column_ordering_strategy: legacy
        physical_naming_strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
    show-sql: false
    properties.hibernate.format_sql: false

  data:
    mongodb:
      uri: mongodb://localhost:27017/passenger_read
      database: passenger_read


  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    template:
      exchange: passenger
      exchange-type: fanout

  otel:
    collector:
      service-name: passenger
      service-version: 1.0.0
      endpoint: http://localhost:4317

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8090/realms/keycloak-realm/protocol/openid-connect/certs
